CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    nickname VARCHAR(255),
    avatar   VARCHAR(255),
    provider VARCHAR(255),
    subject  VARCHAR(255),
    access   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uk_user_openid UNIQUE (provider, subject);